active-application-yml: application.yml in dev

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

api:
  endpoint:
    base-url-users: /api/v1/users
    base-url-jobs: /api/v1/jobs
    base-url-ads: /api/v1/ads

