active-application-yml: application.yml in main

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/headhunter-db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect

api:
  endpoint:
    base-url-users: /api/v1/users
    base-url-jobs: /api/v1/jobs
    base-url-ads: /api/v1/ads

ai:
  openai:
    endpoint: ${OPENAI_API_ENDPOINT} # environment variable with a default value
    # Remember to save API Key in Azure Key Vault when the app goes into production
    #    api-key: ${AI_OPENAI_API_KEY} # environment variable with a default value
    api-key: ${OPENAI_API_KEY} # environment variable with a default value