spring:
  datasource:
    url: jdbc:h2:mem:headhunter
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
api:
  endpoint:
    base-url-users: /api/v1/users
    base-url-jobs: /api/v1/jobs

#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/headhunter-db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
#    username: [username]
#    password: [password]
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect

ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:[OpenAI Endpoint]} # environment variable with a default value
    # Remember to save API Key in Azure Key Vault when the app goes into production
    api-key: ${AI_OPENAI_API_KEY:[OpenAI key]} # environment variable with a default value